import {
  SCHEMA_VERSION,
  type Database,
  type Festival,
  type Edition,
  type Call,
  type Film,
  type Submission,
} from "../types";
export const uid = (prefix: string) => `${prefix}-${crypto.randomUUID()}`;
export const blankSeasonalEstimate = () => ({
  months: [],
  evidenceYears: [],
  confidence: "desconhecida" as const,
  note: "",
});
export const blankRelevance = () => ({
  status: "pendente" as const,
  score: null,
  uncertaintyMin: null,
  uncertaintyMax: null,
  band: "pendente" as const,
  impact: "pendente" as const,
  confidence: "pendente" as const,
  assessedAt: "",
  rationale:
    "Avaliação pendente: as evidências disponíveis ainda não permitem aplicar a rubrica.",
  dimensions: {
    curatorialHistory: { score: null, evidence: "", sourceIds: [] },
    programmingReach: { score: null, evidence: "", sourceIds: [] },
    industryOpportunities: { score: null, evidence: "", sourceIds: [] },
    specializedImportance: { score: null, evidence: "", sourceIds: [] },
    continuityTransparency: { score: null, evidence: "", sourceIds: [] },
  },
});
export const blankFestival = (id = uid("festival")): Festival => ({
  id,
  name: "",
  internationalName: "",
  acronym: "",
  aliases: [],
  country: "Brasil",
  region: "",
  city: "",
  locations: [],
  traveling: false,
  onlineOnly: false,
  website: "",
  instagram: "",
  contact: "",
  organizer: "",
  platforms: [],
  description: "",
  genres: [],
  workTypes: ["filme"],
  languages: [],
  approaches: [],
  contentGenres: [],
  themes: [],
  audiences: [],
  participationConditions: [],
  tags: [],
  scale: "não confirmado",
  frequency: "não confirmado",
  activity: "atividade não confirmada",
  favorite: false,
  priority: "sem prioridade",
  basePriority: "sem prioridade",
  seasonality: {
    opening: blankSeasonalEstimate(),
    event: blankSeasonalEstimate(),
  },
  relevance: blankRelevance(),
  researchCoverage: {},
  personalNotes: "",
  sources: [],
});
export const blankEdition = (
  festivalId: string,
  id = uid("edition"),
): Edition => ({
  id,
  festivalId,
  year: new Date().getFullYear(),
  number: "",
  start: "",
  end: "",
  opening: "",
  closing: "",
  resultDate: "",
  status: "não confirmado",
  rulesUrl: "",
  checkedAt: "",
  confidence: "não verificado",
  notes: "",
  sources: [],
});
export const blankCall = (editionId: string, id = uid("call")): Call => ({
  id,
  editionId,
  name: "",
  formats: [],
  genres: [],
  workTypes: ["filme"],
  languages: [],
  approaches: [],
  contentGenres: [],
  themes: [],
  audiences: [],
  participationConditions: [],
  submissionMode: "não confirmado",
  selectionType: "não confirmado",
  genresConfirmed: false,
  minMinutes: null,
  maxMinutes: null,
  minSeconds: null,
  maxSeconds: null,
  minInclusive: true,
  maxInclusive: true,
  creditsIncluded: null,
  minYear: null,
  maxYear: null,
  pf: "não confirmado",
  pj: "não confirmado",
  premiere: "não confirmado",
  premiereRequirement: "desconhecida",
  premiereTerritory: "",
  premiereConditions: "",
  online: "não confirmado",
  onlineConditions: "",
  countries: [],
  regions: [],
  territoriesConfirmed: false,
  restrictions: "",
  resubmission: "não confirmado",
  platform: "",
  opening: "",
  deadlines: [],
  fees: [],
  rulesUrl: "",
  checkedAt: "",
  confidence: "não verificado",
  notes: "",
  sources: [],
});
export const blankFilm = (id = uid("film")): Film => ({
  id,
  title: "",
  internationalTitle: "",
  year: null,
  minutes: null,
  durationSeconds: null,
  format: "",
  genres: [],
  workType: "filme",
  languages: [],
  approaches: [],
  contentGenres: [],
  themes: [],
  audiences: [],
  participationConditions: [],
  country: "Brasil",
  region: "",
  city: "",
  coproduction: [],
  language: "Português",
  subtitles: [],
  director: "",
  producers: "",
  company: "",
  completionDate: "",
  premiereDate: "",
  premiereCountry: "",
  premiereRegion: "",
  premiereCity: "",
  worldPremiereAvailable: "não confirmado",
  online: "não confirmado",
  onlineStatus: "não informado",
  onlineHistory: [],
  exhibitionHistory: [],
  materials: [],
  cpb: "",
  synopsis: "",
  links: [],
  notes: "",
});
export const blankSubmission = (id = uid("submission")): Submission => ({
  id,
  filmId: "",
  festivalId: "",
  editionId: "",
  callId: "",
  platform: "",
  date: "",
  deadline: "",
  fee: null,
  currency: "BRL",
  code: "",
  status: "planejado",
  planningStatus: "pesquisando",
  sendStatus: "não enviado",
  resultStatus: "pendente",
  personalPriority: "sem prioridade",
  responsible: "",
  protocol: "",
  originalFee: null,
  paidBRL: null,
  waiverUsed: false,
  expectedDecisionDate: "",
  nextAction: "",
  internalDeadline: "",
  checklist: [],
  tasks: [],
  screenings: [],
  awards: [],
  result: "",
  resultDate: "",
  award: "",
  notes: "",
});
export const emptyDatabase = (): Database => ({
  schemaVersion: SCHEMA_VERSION,
  festivals: [],
  editions: [],
  calls: [],
  films: [],
  submissions: [],
  settings: {
    name: "",
    timezone: "America/Sao_Paulo",
    staleDays: 180,
    festivalView: "table",
    lastBackup: "",
    catalogVersion: "",
    pageSize: 50,
    festivalColumns: [
      "favorite",
      "festival",
      "compatibleCall",
      "submissions",
      "deadline",
      "fee",
      "relevance",
      "priority",
    ],
    savedFestivalViews: [],
  },
  archive: {
    excludedFestivals: [],
    importReports: [],
    editHistory: [],
    catalogUpdates: [],
  },
});
